// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9RLYdeG4VOt23RoemO2EHSMd3Vsc_2I',
    appId: '1:458113215854:android:5d6739031e662aa5cb257f',
    messagingSenderId: '458113215854',
    projectId: 'proyecto-final-factores',
    storageBucket: 'proyecto-final-factores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlS3eTwduzG8QgifBi6lL8oqCUZYmoqY',
    appId: '1:458113215854:ios:81f2b0658d84261acb257f',
    messagingSenderId: '458113215854',
    projectId: 'proyecto-final-factores',
    storageBucket: 'proyecto-final-factores.appspot.com',
    iosClientId:
        '458113215854-cc5e0jloqr6u54r421i88m23osskvhb6.apps.googleusercontent.com',
    iosBundleId: 'app.ud.proyectoFinalFactoresApp',
  );
}
